name = "Bright Spin"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"

# Cloudflare Pages configuration
pages_build_output_dir = "out"
